### ISSUE TITLE
Invalid unicode in author email field of README.rst

### ISSUE THREAD

**Issue by zerosignal0** [saghul/aiodns#9] opened 2015-04-16 00:08 UTC
Python 3.4.x is unable to build / install the latest version of this library due to incompatiable unicode used in the authors name/email field.  Removal of this line or usage of conversion tools such as iconv fix the issue.

**Comment by mathieui** [comment] 2015-04-16 07:29
Can't reproduce here, regardless of the chosen locale. The utf-8 used in the setup.py is standard and should not be an issue on python 3.4 where source code files are considered utf-8 by default (and there's a coding statement anyway).

**Comment by saghul** [comment] 2015-04-16 07:29
What error are you getting? IIRC that should be fixed by https://github.com/saghul/aiodns/commit/1b65499d2cc9d5fc3843a65fe7eb50a1175a8990, can you try latest master?

**Comment by zerosignal0** [comment] 2015-04-16 16:14
Hello,

Sorry about the missing content from the issue, my copy / paste failed yesterday.  At any rate the same issues were observed in the issue I opened yesterday on pycares.  Please see my description here:

https://github.com/saghul/pycares/issues/18

ps.
My attempts in the testing / patching of this were performed against the master copy cloned from here.

Regards,
Gary

**Comment by zerosignal0** [comment] 2015-04-17 15:53
Thank you much for the patch in version on pycares! Any chance when you have the chance you may be able to do the same with this project?

THANKS!

**Comment by saghul** [comment] 2015-04-20 06:48
@zerosignal0 here you go! https://github.com/saghul/aiodns/releases/tag/aiodns-0.3.2

**Closed by saghul** 2015-04-20 06:48 UTC

**Comment by zerosignal0** [comment] 2015-04-20 14:57
Thanks!
